#pragma once

// The setup page served by portal.c. Self-contained (no external requests: the phone has no
// internet while it's on the setup network).

static const char PORTAL_PAGE[] =
"<!doctype html><html><head><meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>ABS Player setup</title><style>"
":root{--bg:#101418;--card:#1e252c;--text:#f2f2f2;--muted:#8c96a0;--accent:#f0a030}"
"*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px system-ui,sans-serif}"
"main{max-width:480px;margin:0 auto;padding:16px}h1{font-size:22px;margin:8px 0 16px}"
"h2{font-size:15px;color:var(--accent);margin:0 0 10px;text-transform:uppercase;letter-spacing:.05em}"
"section{background:var(--card);border-radius:12px;padding:14px;margin-bottom:14px}"
"label{display:block;font-size:14px;color:var(--muted);margin:10px 0 4px}"
"input,select{width:100%;padding:10px;border-radius:8px;border:1px solid #333c45;background:#0c1014;color:var(--text);font-size:16px}"
".row{display:flex;gap:10px}.row>div{flex:1}.chk{display:flex;align-items:center;gap:8px;margin-top:12px}"
".chk input{width:auto}.hint{font-size:13px;color:var(--muted);margin-top:6px}"
"button{width:100%;padding:14px;border:0;border-radius:10px;background:var(--accent);color:#000;font-size:17px;font-weight:600}"
"button:disabled{opacity:.5}#status{margin-top:12px;min-height:22px;text-align:center}"
".tabs{display:flex;gap:8px;margin-bottom:4px}.tabs label{flex:1;margin:0;text-align:center;padding:8px;border-radius:8px;background:#0c1014;color:var(--text)}"
".tabs input{display:none}.tabs input:checked+span{color:var(--accent)}"
"</style></head><body><main><h1>ABS Player setup</h1>"
"<section><h2>Wi-Fi</h2>"
"<label for=ssid>Network</label><select id=ssid><option>Scanning...</option></select>"
"<input id=ssid_other placeholder='Network name' style='display:none;margin-top:8px'>"
"<label for=wpass>Password</label><input id=wpass type=password placeholder='Leave blank to keep the saved one'>"
"</section>"
"<section><h2>Audiobookshelf</h2>"
"<label for=server>Server address</label><input id=server placeholder='https://abs.example.com' autocapitalize=off>"
"<div class=hint>Include http:// or https://, and the port if it isn't the default.</div>"
"<label>Sign in with</label><div class=tabs>"
"<label><input type=radio name=auth value=password checked><span>Username</span></label>"
"<label><input type=radio name=auth value=apikey><span>API key</span></label></div>"
"<div id=pw><label for=user>Username</label><input id=user autocapitalize=off>"
"<label for=pass>Password</label><input id=pass type=password></div>"
"<div id=key style='display:none'><label for=apikey>API key</label><input id=apikey autocapitalize=off></div>"
"<div class=hint id=signed></div>"
"</section>"
"<section><h2>Device</h2><div class=row>"
"<div><label for=bright>Brightness</label><select id=bright>"
"<option value=20>20%</option><option value=40>40%</option><option value=60>60%</option><option value=80>80%</option><option value=100>100%</option></select></div>"
"<div><label for=off>Screen off</label><select id=off>"
"<option value=30>30 s</option><option value=60>1 min</option><option value=120>2 min</option><option value=300>5 min</option><option value=0>Never</option></select></div></div>"
"<div class=row><div><label for=sleep>Sleep</label><select id=sleep>"
"<option value=5>5 min</option><option value=10>10 min</option><option value=30>30 min</option><option value=0>Never</option></select></div>"
"<div><label for=skipb>Skip back / fwd</label><div class=row>"
"<select id=skipb><option>10</option><option>15</option><option>30</option><option>60</option></select>"
"<select id=skipf><option>10</option><option>15</option><option>30</option><option>60</option></select></div></div></div>"
"<div class=chk><input type=checkbox id=rotate><label for=rotate style='margin:0;color:var(--text)'>Rotate screen 180&deg;</label></div>"
"</section>"
"<button id=save>Save &amp; connect</button><div id=status></div>"
"</main><script>"
"const $=i=>document.getElementById(i);let cur={};"
"function authMode(){return document.querySelector('input[name=auth]:checked').value}"
"document.querySelectorAll('input[name=auth]').forEach(r=>r.onchange=()=>{$('pw').style.display=authMode()=='password'?'':'none';$('key').style.display=authMode()=='apikey'?'':'none'});"
"$('ssid').onchange=()=>{$('ssid_other').style.display=$('ssid').value=='__other'?'':'none'};"
"function setSel(id,v){const s=$(id);for(const o of s.options)if(o.value==String(v)){s.value=o.value;return}}"
"fetch('/api/config').then(r=>r.json()).then(c=>{cur=c;$('server').value=c.server||'';$('user').value=c.username||'';"
"if(c.auth=='apikey'){document.querySelector('input[value=apikey]').click()}"
"$('signed').textContent=c.signed_in?('Currently signed in'+(c.username?' as '+c.username:'')+'. Leave the password blank to stay signed in.'):'';"
"setSel('bright',c.brightness);setSel('off',c.screen_off);setSel('sleep',c.sleep);setSel('skipb',c.skip_back);setSel('skipf',c.skip_fwd);$('rotate').checked=!!c.rotate;scan()});"
"function scan(){fetch('/api/scan').then(r=>r.json()).then(list=>{const s=$('ssid');s.innerHTML='';"
"const seen=new Set();for(const n of list){if(!n.ssid||seen.has(n.ssid))continue;seen.add(n.ssid);"
"const o=document.createElement('option');o.value=n.ssid;o.textContent=n.ssid+(n.secure?' \\u{1F512}':'');s.appendChild(o)}"
"if(cur.ssid&&!seen.has(cur.ssid)){const o=document.createElement('option');o.value=cur.ssid;o.textContent=cur.ssid+' (saved)';s.prepend(o)}"
"const o=document.createElement('option');o.value='__other';o.textContent='Other network...';s.appendChild(o);"
"if(cur.ssid)s.value=cur.ssid;s.onchange()})}"
"function poll(){fetch('/api/status').then(r=>r.json()).then(st=>{$('status').textContent=st.message;"
"if(st.busy)setTimeout(poll,1000);else $('save').disabled=false}).catch(()=>{$('status').textContent='Reconnect to the setup network if this page stops updating...';setTimeout(poll,2000)})}"
"$('save').onclick=()=>{const b={ssid:$('ssid').value=='__other'?$('ssid_other').value:$('ssid').value,wifi_password:$('wpass').value,"
"server:$('server').value.trim(),auth:authMode(),username:$('user').value.trim(),password:$('pass').value,api_key:$('apikey').value.trim(),"
"brightness:+$('bright').value,screen_off:+$('off').value,sleep:+$('sleep').value,skip_back:+$('skipb').value,skip_fwd:+$('skipf').value,rotate:$('rotate').checked};"
"$('save').disabled=true;$('status').textContent='Saving...';"
"fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}).then(()=>setTimeout(poll,500))};"
"</script></body></html>";
