#pragma once

// Montserrat with accented Latin, Cyrillic, Vietnamese and typographic punctuation, plus the
// LV_SYMBOL_* icons: use these instead of lv_font_montserrat_* (ASCII only) for any text that
// can come from the library. Generated by tools/gen_fonts.sh into fonts/.

#include "lvgl.h"

LV_FONT_DECLARE(ui_font_14)
LV_FONT_DECLARE(ui_font_16)
LV_FONT_DECLARE(ui_font_20)
